### ISSUE TITLE
Hi there, the dataset link seems to be broken. 

### ISSUE THREAD

**Issue by pogevip** [ZZZHANG-jx/DocAligner#1]
By the way, are you planning to open-source the code and model in the future?

**Comment by ZZZHANG-jx** [comment]
Thank you for your attention. 1. I have tested the link and it works fine. It is a shared link from OneDrive. I suspect you may need a network proxy to access it. 2. Yes, we will open-source our code and models.

**Comment by lerndeep** [comment]
@ZZZHANG-jx when you will open your code ?
waiting

**Comment by ZZZHANG-jx** [comment]
> @ZZZHANG-jx when you will open your code ? waiting

Thank you for your attention; our complete code will be open-sourced after the paper is accepted. In case you're interested to make some comparisons or have any problems with the paper, please feel free to contact me.
