### ISSUE TITLE
Reproduction of generating flow field

### ISSUE THREAD

**Issue by Snailpong** [ZZZHANG-jx/DocAligner#2]
Hello, I was deeply impressed by your outstanding research work.
I am currently concentrating on Appendix C of your paper, as I am endeavoring to construct a dataset based on it.
I've attempted to reproduce it, but regrettably, I encountered difficulties, which is why I've created this issue.

- The final flow field must increase continuously, but is this part applied in Eq.13?
I don't know if scaling_x and scaling_y have different values for each index, or if scaling_x and scaling_y are just one scaler. If the values for each index are different, I wonder if you did any additional processing, such as a filter. 
I'm also curious why the values are [-0.05, 0.2], can be less than 0. In my case for reproducing, I changed -0.05 to 0.05.

- I wonder if there is no separate weight in scaling. This is because if weight is not given, warping fails in my reproduce. In addition, the part of calculating f and then normalizing minmax was not mentioned. Please check if this is correct.

I attached a code below. If there are any problematic parts, I would appreciate it if you could point them out.

```python
import cv2
import numpy as np
from scipy.ndimage import uniform_filter

f = np.random.uniform(-4096, 4096, size=(1024, 1024, 2))

f = uniform_filter(f, size=91)
f = uniform_filter(f, size=91)

# Add global distortion by considering translation and scaling
translation_x = np.random.uniform(-50, 50)
translation_y = np.random.uniform(-50, 50)

f[..., 0] += translation_x
f[..., 1] += translation_y

# scaling = np.random.uniform(-0.05, 0.2, (1024, 1024, 2))  # right?
scaling_x = np.random.uniform(0.05, 0.2)   # my reproducing
scaling_y = np.random.uniform(0.05, 0.2)

base_coordinate = np.indices((1024, 1024)).transpose(1, 2, 0)

# Eq. 13. Apply the translation and scaling to the flow field
# Weighting 20 for my reproducing
f[..., 0] += (base_coordinate[..., 0] - 512) * scaling_x * 20
f[..., 1] += (base_coordinate[..., 1] - 512) * scaling_y * 20

# Minmax normalizing
f[..., 0] = (f[..., 0] - np.min(f[..., 0])) / (np.max(f[..., 0]) - np.min(f[..., 0])) * 1023
f[..., 1] = (f[..., 1] - np.min(f[..., 1])) / (np.max(f[..., 1]) - np.min(f[..., 1])) * 1023


# Load an image
img = cv2.imread(image_path)
img = cv2.resize(img, (1024, 1024))

# Create x and y maps for remapping
# map_x = np.add(np.indices((1024, 1024))[1], f[..., 0])
# map_y = np.add(np.indices((1024, 1024))[0], f[..., 1])
map_x, map_y = f[..., 1], f[..., 0]

# Remap the image using the flow field
warped_img = cv2.remap(
    img.astype("float32"),
    map_x.astype("float32"),
    map_y.astype("float32"),
    interpolation=cv2.INTER_LINEAR,
)

warped_img_uint8 = cv2.convertScaleAbs(warped_img)
```

![image](https://github.com/ZZZHANG-jx/DocAligner/assets/11583179/aa241cbe-028f-4c61-b4cb-ecbdfafcbfda)

**Comment by ZZZHANG-jx** [comment]
Thank you for your interest. I have uploaded our code for synthesizing the flow field, which you can use as a reference.
