### ISSUE TITLE
Any plan to release the source code?

### ISSUE THREAD

**Issue by yflv-yanxia** [ZZZHANG-jx/DocAligner#3]
Any plan to release the source code? Thank you!

**Comment by ZZZHANG-jx** [comment]
Yes, our complete code will be open-sourced after the paper is accepted. In case you're interested to make some comparisons or have any problems with the paper, please feel free to contact me.

**Comment by yflv-yanxia** [comment]
Looking forward to the day...

**Comment by ZZZHANG-jx** [comment]
Sorry for the delay in the open-source plan. We have uploaded the inference code in the latest commit. The training code and data will be open-sourced gradually. Thank you for your interest in our work!

**Comment by ZZZHANG-jx** [comment]
Hi @yflv-yanxia and @lerndeep,

Thank you for your interest and patience! I'm pleased to inform you that the training and testing code has now been open-sourced. 

Feel free to explore it, and don't hesitate to reach out if you encounter any issues or have further questions.

Thanks again for your support!
