### ISSUE TITLE
你好，请问你们现在这篇文章在投哪个期刊了吗

### ISSUE THREAD

**Issue by hanmiaolingit** [ZZZHANG-jx/DocAligner#4]

**Comment by ZZZHANG-jx** [comment]
感谢关注，近期准备开源了

**Comment by ZZZHANG-jx** [comment]
感谢关注，近期准备开源了

**Comment by daeing** [comment]
> 感谢关注，近期准备开源了

您好，请问开源计划是什么样的呢？比如大概几周后会开源？期待您的回复。

**Comment by ZZZHANG-jx** [comment]
> > 感谢关注，近期准备开源了
> 
> 您好，请问开源计划是什么样的呢？比如大概几周后会开源？期待您的回复。

9月份完成

**Comment by ZZZHANG-jx** [comment]
> > 感谢关注，近期准备开源了
> 
> 您好，请问开源计划是什么样的呢？比如大概几周后会开源？期待您的回复。

抱歉开源计划有所推迟，我们已经在最新的commit中上传了前向代码。训练代码和数据也会在陆续开源。感谢对我们的工作的关注！

**Comment by ZZZHANG-jx** [comment]
训练代码也已经开源，感谢大家关注
