### ISSUE TITLE
Training code release

### ISSUE THREAD

**Issue by lerndeep** [ZZZHANG-jx/DocAligner#5]
@ZZZHANG-jx 
thank you for your great work.
Now I am working on your training code. Could you please let me know when you are planning to open?

Thank you

**Comment by ZZZHANG-jx** [comment]
> @ZZZHANG-jx thank you for your great work. Now I am working on your training code. Could you please let me know when you are planning to open?
> 
> Thank you

Apologies for the slow progress—I’ll do my best to complete this work by the end of this month. It would be great if you could give the project a star in the meantime!

**Comment by ZZZHANG-jx** [comment]
Hi  @lerndeep ,

Thank you for your patience! I’m glad to let you know that the training code has now been open-sourced. Feel free to check it out, and let me know if you have any questions or need any assistance.

Thanks again for your support!
